// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qqolkvwhjdxayrsadjfd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFxb2xrdndoamR4YXlyc2FkamZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MDY5NzMsImV4cCI6MjA3MDA4Mjk3M30.sxPiY2j2Qn82e72M2Y3aCWAbiH4IkmPI0M9uvleVZqg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});